use_frameworks!

platform :ios, "9.0"

def pod_libraries 
  pod 'Moya-Argo', :path => "../"
  pod 'Moya-Argo/ReactiveCocoa', :path => "../"
  pod 'Moya-Argo/RxSwift', :path => "../"
  pod "Curry", "~> 3.0.0"
end

target 'Moya-Argo_Example' do
 
  pod_libraries

  pod "Cartography"
end

target 'Moya-Argo_Tests' do
  pod_libraries
end
